def recipe($a;$b;$class): {dominantAlbedo:$a,secondaryAlbedo:$b,materialClass:$class,materialClassConfidence:0.9,colorGradient:{type:"radial",stops:[{position:0,color:$a},{position:1,color:$b}]}};
def pbr($id): {usable:true,confidence:0.86,estimatedFidelity:0.86,targetThreshold:0.7,sourceImage:"design/antique-theme/baoshi-v2/baoshi-concept-sheet-v1.png",maps:{albedo:{path:("design/antique-theme/baoshi-v2/reference-pbr/"+$id+"/"+$id+"_albedo.png"),url:($id+"_albedo.png")},roughness:{path:("design/antique-theme/baoshi-v2/reference-pbr/"+$id+"/"+$id+"_roughness.png"),url:($id+"_roughness.png")},height:{path:("design/antique-theme/baoshi-v2/reference-pbr/"+$id+"/"+$id+"_height.png"),url:($id+"_height.png")},normal:{path:("design/antique-theme/baoshi-v2/reference-pbr/"+$id+"/"+$id+"_normal.png"),url:($id+"_normal.png")},ao:{path:("design/antique-theme/baoshi-v2/reference-pbr/"+$id+"/"+$id+"_ao.png"),url:($id+"_ao.png")}}};
def attach($parent): {parentId:$parent,parentSocket:($parent+"-surface"),localStart:[0,0,0],localEnd:[0,0,0.04],contactType:"overlap",overlap:0.025,gapTolerance:0.01,evidenceRefs:["hero","top","side"]};

. as $spec
| .preSpecAssessment.objectClass={primaryType:"octagonal-jade-gem-setting",primaryDomain:"object",formLanguage:["octagonal","stepped-facet","low-bezel","four-prong"],structureKind:["cut-gem-solid","nested-setting","radial-array"],motionPotential:["rigid-body","flat-spin"],materialFamilies:["emerald-jade","antique-gold"],notes:"A compact collectible identified by a broad dark-green table, stepped crown, deep pavilion, octagonal gold bezel, and four protective prongs."}
| .preSpecAssessment.complexity.scores={silhouetteComplexity:2,componentCount:2,hierarchyDepth:2,repetitionDensity:2,materialLayerCount:2,localDetailDensity:2,occlusionRisk:1,actionReadinessNeed:1}
| .preSpecAssessment.complexity.estimatedCounts={macroComponents:4,mesoComponents:3,microFeatureGroups:2,materialLayers:2,repetitionSystems:2}
| .preSpecAssessment.specDepthDecision.needsRepetitionSystems=true
| .preSpecAssessment.specDepthDecision.needsMaterialLocalOverrides=true
| .preSpecAssessment.unknownsToResolveBeforeImplementation=[]
| .preSpecAssessment.detailInventory.details=[
 {id:"broad-table",kind:"ridge",description:"Single uninterrupted dark-green octagonal table",region:{x:0.08,y:0.06,width:0.62,height:0.58,units:"normalized"},scale:"macro",affects:"identity and stable thumbnail color",mapsTo:{type:"component.localFeatures",ref:"table-plane"},evidenceRef:"hero",confidence:0.98},
 {id:"stepped-crown",kind:"ridge",description:"Two octagonal crown bands around the table",region:{x:0.04,y:0.04,width:0.72,height:0.66,units:"normalized"},scale:"meso",affects:"facet highlight and depth",mapsTo:{type:"component.localFeatures",ref:"crown-bands"},evidenceRef:"top",confidence:0.97},
 {id:"deep-pavilion",kind:"ridge",description:"Tapered lower pavilion visible from the side",region:{x:0.23,y:0.60,width:0.5,height:0.32,units:"normalized"},scale:"meso",affects:"side silhouette",mapsTo:{type:"component.localFeatures",ref:"pavilion-taper"},evidenceRef:"side",confidence:0.95},
 {id:"gold-bezel",kind:"ridge",description:"Continuous raised octagonal bezel around the girdle",region:{x:0.02,y:0.03,width:0.76,height:0.7,units:"normalized"},scale:"meso",affects:"material separation",mapsTo:{type:"component.localFeatures",ref:"raised-bezel"},evidenceRef:"hero",confidence:0.96},
 {id:"four-prongs",kind:"ridge",description:"Four broad gold prongs overlapping the gem girdle",region:{x:0.03,y:0.05,width:0.75,height:0.7,units:"normalized"},scale:"micro",affects:"setting credibility",mapsTo:{type:"component.localFeatures",ref:"protective-prongs"},evidenceRef:"top",confidence:0.96},
 {id:"lotus-panels",kind:"ridge",description:"Eight restrained low lotus panels on the setting wall",region:{x:0.05,y:0.48,width:0.72,height:0.34,units:"normalized"},scale:"micro",affects:"ancient setting character",mapsTo:{type:"component.localFeatures",ref:"radial-lotus-panels"},evidenceRef:"side",confidence:0.9}
]
| .viewEvidence=[{id:"hero",view:"three-quarter",imageRegion:{x:0,y:0,width:0.6,height:0.68,units:"normalized"},observations:["dark octagonal table","stepped crown","gold bezel","four prongs"],confidence:0.97},{id:"top",view:"top",imageRegion:{x:0.54,y:0.02,width:0.46,height:0.55,units:"normalized"},observations:["octagonal proportions","four-prong layout","continuous bezel"],confidence:0.97},{id:"side",view:"side",imageRegion:{x:0.18,y:0.56,width:0.72,height:0.43,units:"normalized"},observations:["pavilion depth","low setting","lotus panels"],confidence:0.95},{id:"game",view:"fixed-game-camera",imageRegion:{x:0,y:0,width:1,height:1,units:"normalized"},observations:["mobile pile readability"],confidence:1.0}]
| ($spec.componentTree[0]) as $b
| .componentTree=[
 ($b|.id="root"|.name="Jade Gem Assembly"|.role="container"|.primitive="cylinder"|.topologyClass="assembled-solid"|.topologyRationale="Root groups a cut gem and compact nested gold setting."|.material="emerald"|.materialLayers=["emerald","gold"]|.localFeatures=[]|.colorMaterialRecipe=recipe("rgba(10,76,25,1)";"rgba(120,60,8,1)";"stone")|.evidenceRefs=["hero","top"]),
 ($b|.id="cut-gem"|.name="Octagonal cut jade"|.role="body"|.level="macro"|.parent="root"|.attachment=attach("root")|.primitive="extrude"|.topologyClass="continuous-sculpt"|.topologyRationale="One manifold mesh joins table, crown, girdle, and pavilion section rings."|.material="emerald"|.materialLayers=["emerald"]|.localFeatures=[{id:"table-plane",type:"ridge",placement:"top center",size:0.62,orientation:"horizontal octagon",geometryEffect:"broad coplanar octagonal table",materialEffect:"stable deep emerald",confidence:0.98},{id:"pavilion-taper",type:"deformation",placement:"below girdle",size:0.48,orientation:"downward",geometryEffect:"two-stage tapered pavilion",materialEffect:"deep green facets",confidence:0.95}]|.colorMaterialRecipe=recipe("rgba(8,74,22,1)";"rgba(22,150,58,1)";"stone")|.evidenceRefs=["hero","top","side"]),
 ($b|.id="setting-base"|.name="Octagonal setting base"|.role="support"|.level="macro"|.parent="root"|.attachment=attach("root")|.primitive="cylinder"|.topologyClass="assembled-solid"|.topologyRationale="A low beveled octagonal solid supports the pavilion without forming a finger ring."|.material="gold"|.materialLayers=["gold"]|.localFeatures=[]|.colorMaterialRecipe=recipe("rgba(91,33,3,1)";"rgba(177,79,8,1)";"metal")|.evidenceRefs=["hero","side"]),
 ($b|.id="bezel"|.name="Raised octagonal bezel"|.role="rim"|.level="macro"|.parent="setting-base"|.attachment=attach("setting-base")|.primitive="torus"|.topologyClass="continuous-sculpt"|.topologyRationale="A continuous low-profile octagonal rim overlaps the gem girdle."|.material="gold"|.materialLayers=["gold"]|.localFeatures=[{id:"raised-bezel",type:"ridge",placement:"around girdle",size:0.075,orientation:"octagonal radial",geometryEffect:"continuous raised perimeter",materialEffect:"warm edge highlight",confidence:0.96}]|.colorMaterialRecipe=recipe("rgba(130,57,7,1)";"rgba(205,112,21,1)";"metal")|.evidenceRefs=["hero","top"]),
 ($b|.id="crown-facets"|.name="Stepped crown facet system"|.role="surface-relief"|.level="meso"|.parent="cut-gem"|.attachment=attach("cut-gem")|.primitive="extrude"|.topologyClass="surface-relief"|.topologyRationale="Two octagonal face bands transition from girdle to the broad table."|.material="emerald"|.materialLayers=["emerald"]|.localFeatures=[{id:"crown-bands",type:"ridge",placement:"between table and girdle",size:0.26,orientation:"eight radial sectors",geometryEffect:"sixteen planar transition facets",materialEffect:"alternating green highlight",confidence:0.97}]|.colorMaterialRecipe=recipe("rgba(18,132,48,1)";"rgba(68,190,92,1)";"stone")|.evidenceRefs=["hero","top"]),
 ($b|.id="prong-system"|.name="Four protective gold prongs"|.role="connector"|.level="meso"|.parent="setting-base"|.attachment=attach("setting-base")|.primitive="box"|.topologyClass="assembled-solid"|.topologyRationale="Four beveled solids bridge the setting base and gem girdle with visible overlap."|.material="gold"|.materialLayers=["gold"]|.localFeatures=[{id:"protective-prongs",type:"ridge",placement:"four diagonal positions",size:0.24,orientation:"radial",geometryEffect:"broad rounded claws crossing the girdle",materialEffect:"gold highlight and contact AO",confidence:0.96}]|.colorMaterialRecipe=recipe("rgba(151,69,8,1)";"rgba(221,131,27,1)";"metal")|.evidenceRefs=["hero","top","side"]),
 ($b|.id="lotus-panels"|.name="Low lotus setting panels"|.role="ornament"|.level="meso"|.parent="setting-base"|.attachment=attach("setting-base")|.primitive="instanced-cluster"|.topologyClass="assembled-solid"|.topologyRationale="Eight low faceted petals repeat around the setting wall without covering the table."|.material="gold"|.materialLayers=["gold"]|.localFeatures=[{id:"radial-lotus-panels",type:"ridge",placement:"setting outer wall",size:0.16,orientation:"radial",geometryEffect:"eight compressed faceted petals",materialEffect:"alternating gold planes",confidence:0.9}]|.colorMaterialRecipe=recipe("rgba(118,45,4,1)";"rgba(193,91,11,1)";"metal")|.evidenceRefs=["hero","side"])
]
| ($spec.materials[0]) as $m
| .materials=[
 ($m|.id="emerald"|.name="Deep emerald jade"|.baseColor="#0B5D21"|.color="#0B5D21"|.roughness.base=0.27|.metalness=0.01|.localOverrides=[{id:"crown-highlight",region:"selected crown sectors only",color:"#2A9E4B",roughness:0.2,strength:0.42,evidenceRefs:["hero","top"]},{id:"pavilion-depth",region:"lower pavilion",color:"#053315",roughness:0.32,strength:0.55,evidenceRefs:["side"]}]|.referencePbr=pbr("emerald")),
 ($m|.id="gold"|.name="Antique gold setting"|.baseColor="#8B3E08"|.color="#8B3E08"|.roughness.base=0.39|.metalness=0.48|.localOverrides=[{id:"setting-recess",region:"base wall and prong roots",color:"#4B1702",roughness:0.62,strength:0.5,evidenceRefs:["hero","side"]},{id:"worn-rim",region:"bezel and prong high edges",color:"#D78A25",roughness:0.3,strength:0.35,evidenceRefs:["hero","top"]}]|.referencePbr=pbr("gold"))
]
| .repetitionSystems=[{id:"eight-crown-sectors",type:"radial-array",count:8,componentRef:"crown-facets",distribution:"octagonal crown around table",geometry:{innerRadius:0.62,outerRadius:0.92},buildsGeometry:true,evidenceRefs:["hero","top"]},{id:"four-prongs",type:"radial-array",count:4,componentRef:"prong-system",distribution:"diagonal setting positions",geometry:{radius:0.82,overlap:0.08},buildsGeometry:true,evidenceRefs:["hero","top","side"]}]
| .featureReviewTargets=[{id:"octagonal-gem",name:"Broad table, stepped crown and deep pavilion",tier:"critical",passIds:["blockout","form-refinement"],minimumScore:0.88,mustPass:true,componentRefs:["cut-gem","crown-facets"],evidenceRefs:["hero","top","side"]},{id:"gold-setting",name:"Low octagonal base and continuous bezel",tier:"critical",passIds:["structural-pass","form-refinement"],minimumScore:0.85,mustPass:true,componentRefs:["setting-base","bezel"],evidenceRefs:["hero","side"]},{id:"prong-attachment",name:"Four overlapping protective prongs",tier:"critical",passIds:["structural-pass","surface-pass"],minimumScore:0.85,mustPass:true,componentRefs:["prong-system"],evidenceRefs:["hero","top"]},{id:"emerald-gold-separation",name:"Deep emerald and aged-gold material separation",tier:"critical",passIds:["material-pass","lighting-pass"],minimumScore:0.84,mustPass:true,componentRefs:["cut-gem","bezel","setting-base"],evidenceRefs:["hero","game"]},{id:"game-readability",name:"Mobile fixed-camera gem readability",tier:"critical",passIds:["optimization-pass"],minimumScore:0.84,mustPass:true,componentRefs:["root","cut-gem","prong-system"],evidenceRefs:["game"]}]
| .lightingFromPhoto=["key light: broad warm upper-left light reveals crown planes and gold rim","fill light: cool low-intensity right fill preserves the dark emerald table","rim/environment: restrained neutral environment reflection; opaque jade must not disappear","contact shadow: soft coherent ground shadow under the low setting proves pavilion depth","exposure: 0.0; tone mapping: AgX Medium High Contrast"]
| .qualityTargets.targetFidelity=0.86
| .qualityTargets.reviewViewpoints=["fixed-game-three-quarter","top","side","back"]
| .performanceBudget={qualityPriority:"mobile silhouette and facet hierarchy",targetTriangles:1500,maxTriangles:3000,maxDrawCalls:6,textureSize:512,fpsTarget:60,optimizationPolicy:"Preserve table, crown, pavilion, bezel and four prongs; simplify hidden underside lotus facets first."}
| .buildPasses|=map(.componentRefs=["root","cut-gem","setting-base","bezel","crown-facets","prong-system","lotus-panels"])
| .risks=["Transparent gemstone shading is intentionally avoided because dense Cocos pile lighting can make the item disappear.","The setting remains a compact base and must never become a finger ring silhouette.","Single-image PBR maps are evidence only; runtime lighting remains the material authority."]
