def recipe($a;$b;$class): {dominantAlbedo:$a,secondaryAlbedo:$b,materialClass:$class,materialClassConfidence:0.9,colorGradient:{type:"linear",stops:[{position:0,color:$a},{position:1,color:$b}]}};
def pbr($id): {usable:true,confidence:0.86,estimatedFidelity:0.86,targetThreshold:0.7,sourceImage:"design/antique-theme/banzhi-v2/banzhi-concept-sheet-v2.png",maps:{albedo:{path:("design/antique-theme/banzhi-v2/reference-pbr/"+$id+"/"+$id+"_albedo.png"),url:($id+"_albedo.png")},roughness:{path:("design/antique-theme/banzhi-v2/reference-pbr/"+$id+"/"+$id+"_roughness.png"),url:($id+"_roughness.png")},height:{path:("design/antique-theme/banzhi-v2/reference-pbr/"+$id+"/"+$id+"_height.png"),url:($id+"_height.png")},normal:{path:("design/antique-theme/banzhi-v2/reference-pbr/"+$id+"/"+$id+"_normal.png"),url:($id+"_normal.png")},ao:{path:("design/antique-theme/banzhi-v2/reference-pbr/"+$id+"/"+$id+"_ao.png"),url:($id+"_ao.png")}}};
def attach($parent): {parentId:$parent,parentSocket:($parent+"-surface"),localStart:[0,0,0],localEnd:[0,0,0.03],contactType:"overlap",overlap:0.02,gapTolerance:0.01,evidenceRefs:["hero","top","side"]};

. as $spec
| .preSpecAssessment.objectClass={primaryType:"celadon-honey-jade-thumb-ring",primaryDomain:"object",formLanguage:["plump-barrel","sloped-lip","open-center","hand-polished"],structureKind:["continuous-ring","open-liner","surface-inclusions","applied-relief"],motionPotential:["rigid-body","tumble","flat-spin"],materialFamilies:["celadon-jade","honey-russet","turquoise","champagne-gold"],notes:"A plump open thumb ring in pale celadon jade, with milky inclusions, restrained honey-russet skin, a sloped upper lip, champagne-gold liner, and readable mountain-cloud relief."}
| .preSpecAssessment.complexity.scores={silhouetteComplexity:3,componentCount:3,hierarchyDepth:2,repetitionDensity:2,materialLayerCount:3,localDetailDensity:3,occlusionRisk:2,actionReadinessNeed:1}
| .preSpecAssessment.complexity.estimatedCounts={macroComponents:3,mesoComponents:3,microFeatureGroups:2,materialLayers:3,repetitionSystems:2}
| .preSpecAssessment.specDepthDecision.needsRepetitionSystems=true
| .preSpecAssessment.specDepthDecision.needsMaterialLocalOverrides=true
| .preSpecAssessment.unknownsToResolveBeforeImplementation=[]
| .preSpecAssessment.detailInventory.details=[
 {id:"plump-barrel",kind:"contour",description:"Full thick-walled barrel silhouette",region:{x:0.05,y:0.08,width:0.62,height:0.72,units:"normalized"},scale:"macro",affects:"thumb-ring recognition",mapsTo:{type:"component.localFeatures",ref:"full-barrel"},evidenceRef:"hero",confidence:0.98},
 {id:"sloped-lip",kind:"contour",description:"Asymmetric polished upper lip",region:{x:0.08,y:0.06,width:0.58,height:0.28,units:"normalized"},scale:"macro",affects:"premium hand-cut silhouette",mapsTo:{type:"component.localFeatures",ref:"sloped-opening"},evidenceRef:"top",confidence:0.98},
 {id:"true-opening",kind:"hole",description:"Continuous open center and visible inner wall",region:{x:0.2,y:0.12,width:0.32,height:0.34,units:"normalized"},scale:"macro",affects:"ring identity",mapsTo:{type:"component.localFeatures",ref:"open-center"},evidenceRef:"top",confidence:0.99},
 {id:"milky-inclusions",kind:"stain",description:"Soft milky white clouds inside pale celadon",region:{x:0.06,y:0.08,width:0.62,height:0.7,units:"normalized"},scale:"meso",affects:"jade credibility",mapsTo:{type:"material.localOverrides",ref:"milky-clouds"},evidenceRef:"hero",confidence:0.96},
 {id:"celadon-roots",kind:"stain",description:"Continuous low-contrast aqua color roots",region:{x:0.06,y:0.08,width:0.62,height:0.7,units:"normalized"},scale:"meso",affects:"natural stone variation",mapsTo:{type:"material.localOverrides",ref:"aqua-roots"},evidenceRef:"hero",confidence:0.95},
 {id:"honey-skin",kind:"stain",description:"Localized honey-russet side inclusion rather than a dark full band",region:{x:0.5,y:0.42,width:0.2,height:0.28,units:"normalized"},scale:"meso",affects:"warm color contrast",mapsTo:{type:"material.localOverrides",ref:"localized-honey"},evidenceRef:"side",confidence:0.96},
 {id:"mountain-cloud",kind:"ridge",description:"Broad turquoise mountain-cloud relief with restrained gold ridge",region:{x:0.08,y:0.45,width:0.58,height:0.24,units:"normalized"},scale:"meso",affects:"front orientation and antique identity",mapsTo:{type:"component.localFeatures",ref:"mountain-cloud-lines"},evidenceRef:"hero",confidence:0.97}
]
| .viewEvidence=[{id:"hero",view:"three-quarter",imageRegion:{x:0,y:0,width:0.7,height:0.82,units:"normalized"},observations:["plump barrel","pale celadon body","mountain-cloud relief"],confidence:0.98},{id:"top",view:"top",imageRegion:{x:0.62,y:0.03,width:0.38,height:0.48,units:"normalized"},observations:["sloped lip","true opening","gold liner"],confidence:0.97},{id:"side",view:"side",imageRegion:{x:0.15,y:0.72,width:0.82,height:0.28,units:"normalized"},observations:["localized honey skin","thick wall","stable base"],confidence:0.96},{id:"game",view:"fixed-game-camera",imageRegion:{x:0,y:0,width:1,height:1,units:"normalized"},observations:["mobile pile readability"],confidence:1.0}]
| ($spec.componentTree[0]) as $b
| .componentTree=[
 ($b|.id="root"|.name="Celadon Honey Jade Thumb Ring Assembly"|.role="container"|.primitive="cylinder"|.topologyClass="assembled-solid"|.topologyRationale="Root groups the thick open jade body, inner liner and applied relief."|.material="jade"|.materialLayers=["jade","gold","turquoise"]|.localFeatures=[]|.colorMaterialRecipe=recipe("rgba(155,211,201,1)";"rgba(221,235,225,1)";"stone")|.evidenceRefs=["hero","top","side"]),
 ($b|.id="jade-body"|.name="Sloped open jade barrel"|.role="body"|.level="macro"|.parent="root"|.attachment=attach("root")|.primitive="lathe"|.topologyClass="continuous-sculpt"|.topologyRationale="A single manifold thick-walled ring preserves the open center and asymmetric lip."|.material="jade"|.materialLayers=["jade"]|.localFeatures=[{id:"full-barrel",type:"deformation",placement:"entire body",size:1.0,orientation:"vertical",geometryEffect:"plump slightly tapered barrel",materialEffect:"broad soft highlights",confidence:0.98},{id:"sloped-opening",type:"contour",placement:"upper lip",size:0.7,orientation:"asymmetric",geometryEffect:"smooth rising lip",materialEffect:"bright polished rim",confidence:0.98},{id:"open-center",type:"hole",placement:"central axis",size:0.55,orientation:"through",geometryEffect:"real uninterrupted opening",materialEffect:"inner-wall shading",confidence:0.99}]|.colorMaterialRecipe=recipe("rgba(158,213,202,1)";"rgba(221,235,225,1)";"stone")|.evidenceRefs=["hero","top","side"]),
 ($b|.id="jade-inclusions"|.name="Milky cloud and aqua root field"|.role="surface-relief"|.level="meso"|.parent="jade-body"|.attachment=attach("jade-body")|.primitive="cylinder"|.topologyClass="material-only"|.topologyRationale="Continuous wrapped maps carry inclusions without dark seams or raised mosaic geometry."|.material="jade"|.materialLayers=["jade"]|.localFeatures=[{id:"continuous-inclusions",type:"stain",placement:"wrapped body",size:0.7,orientation:"flowing",geometryEffect:"none",materialEffect:"milky clouds and aqua roots",confidence:0.96}]|.colorMaterialRecipe=recipe("rgba(215,234,225,1)";"rgba(95,169,158,1)";"stone")|.evidenceRefs=["hero","top"]),
 ($b|.id="gold-liner"|.name="Open champagne-gold inner liner"|.role="lining"|.level="macro"|.parent="jade-body"|.attachment=attach("jade-body")|.primitive="cylinder"|.topologyClass="conforming-shell"|.topologyRationale="Thin open shell follows the inner wall and lip while preserving the real hole."|.material="gold"|.materialLayers=["gold"]|.localFeatures=[{id:"thin-liner",type:"rim",placement:"inner wall and lip",size:0.45,orientation:"concentric",geometryEffect:"open conforming shell",materialEffect:"soft champagne highlight",confidence:0.97}]|.colorMaterialRecipe=recipe("rgba(184,133,61,1)";"rgba(229,190,112,1)";"metal")|.evidenceRefs=["hero","top"]),
 ($b|.id="turquoise-relief"|.name="Mountain-cloud jade relief"|.role="ornament"|.level="meso"|.parent="jade-body"|.attachment=attach("jade-body")|.primitive="curve-sweep"|.topologyClass="assembled-solid"|.topologyRationale="Broad conforming curves form readable mountains and cloud spirals on the camera-facing wall."|.material="turquoise"|.materialLayers=["turquoise"]|.localFeatures=[{id:"mountain-cloud-lines",type:"ridge",placement:"front lower wall",size:0.6,orientation:"horizontal",geometryEffect:"three mountain peaks and two cloud spirals",materialEffect:"saturated turquoise contrast",confidence:0.97}]|.colorMaterialRecipe=recipe("rgba(31,141,130,1)";"rgba(93,196,179,1)";"stone")|.evidenceRefs=["hero"]),
 ($b|.id="gold-ridges"|.name="Restrained worn gold ridges"|.role="trim"|.level="meso"|.parent="turquoise-relief"|.attachment=attach("turquoise-relief")|.primitive="curve-sweep"|.topologyClass="assembled-solid"|.topologyRationale="Thin gold lines touch only the upper mountain ridges and do not overpower the jade."|.material="gold"|.materialLayers=["gold"]|.localFeatures=[{id:"worn-ridge",type:"edge-wear",placement:"mountain upper edges",size:0.18,orientation:"along relief",geometryEffect:"thin raised accent",materialEffect:"worn champagne gold",confidence:0.94}]|.colorMaterialRecipe=recipe("rgba(185,125,42,1)";"rgba(231,190,95,1)";"metal")|.evidenceRefs=["hero"])
]
| ($spec.materials[0]) as $m
| .materials=[
 ($m|.id="jade"|.name="Milky pale celadon jade"|.baseColor="#9BD3C9"|.color="#9BD3C9"|.roughness.base=0.34|.metalness=0.0|.localOverrides=[{id:"milky-clouds",region:"broad soft fields",color:"#DDEBE1",roughness:0.37,strength:0.52,evidenceRefs:["hero","top"]},{id:"aqua-roots",region:"continuous flowing roots",color:"#5FA99E",roughness:0.33,strength:0.22,evidenceRefs:["hero"]},{id:"localized-honey",region:"one lower side patch only",color:"#A86524",roughness:0.42,strength:0.58,evidenceRefs:["hero","side"]}]|.referencePbr=pbr("jade")),
 ($m|.id="gold"|.name="Soft champagne gold"|.baseColor="#B8853D"|.color="#B8853D"|.roughness.base=0.5|.metalness=0.38|.localOverrides=[{id:"worn-ridges",region:"relief ridge accents",color:"#E2B75B",roughness:0.38,strength:0.35,evidenceRefs:["hero"]}]|.referencePbr=pbr("gold")),
 ($m|.id="turquoise"|.name="Carved turquoise relief"|.baseColor="#1F8D82"|.color="#1F8D82"|.roughness.base=0.38|.metalness=0.0|.localOverrides=[{id:"carved-recess",region:"cloud spiral recesses",color:"#11645F",roughness:0.46,strength:0.25,evidenceRefs:["hero"]}]|.referencePbr=pbr("honey"))
]
| .repetitionSystems=[{id:"wrapped-inclusion-field",type:"linear-array",count:8,componentRef:"jade-inclusions",distribution:"overlapping multi-frequency fields around wrapped UV",geometry:{spacing:0.125,overlap:0.55},buildsGeometry:false,evidenceRefs:["hero","top","side"]},{id:"mountain-cloud-system",type:"linear-array",count:5,componentRef:"turquoise-relief",distribution:"three peaks and two cloud spirals across front",geometry:{spacing:0.18,overlap:0.04},buildsGeometry:true,evidenceRefs:["hero"]}]
| .featureReviewTargets=[{id:"ring-silhouette",name:"Plump sloped open thumb-ring silhouette",tier:"critical",passIds:["blockout","form-refinement"],minimumScore:0.9,mustPass:true,componentRefs:["jade-body","gold-liner"],evidenceRefs:["hero","top","side"]},{id:"jade-material",name:"Pale celadon jade with milky clouds, aqua roots and no black lower band",tier:"critical",passIds:["surface-pass","material-pass","lighting-pass"],minimumScore:0.9,mustPass:true,componentRefs:["jade-body","jade-inclusions"],evidenceRefs:["hero","top","side"]},{id:"localized-honey",name:"Warm honey-russet remains a local side inclusion rather than a full dark base",tier:"critical",passIds:["material-pass"],minimumScore:0.86,mustPass:true,componentRefs:["jade-inclusions"],evidenceRefs:["hero","side"]},{id:"mountain-cloud-read",name:"Turquoise mountain-cloud relief and restrained gold ridge remain readable",tier:"critical",passIds:["structural-pass","form-refinement"],minimumScore:0.85,mustPass:true,componentRefs:["turquoise-relief","gold-ridges"],evidenceRefs:["hero"]},{id:"game-readability",name:"Open center and pale jade body survive the mobile fixed camera",tier:"critical",passIds:["optimization-pass","lighting-pass"],minimumScore:0.84,mustPass:true,componentRefs:["root","jade-body"],evidenceRefs:["game"]}]
| .lightingFromPhoto=["key light: broad warm upper-left light defines the sloped polished lip","fill light: cool frontal fill preserves pale jade color in the lower barrel","rim/environment: soft neutral reflection reveals the thick open center","contact shadow: restrained soft shadow anchors the ring without creating a black base","exposure: 0.0; tone mapping: AgX Medium High Contrast"]
| .qualityTargets.targetFidelity=0.9
| .qualityTargets.reviewViewpoints=["fixed-game-three-quarter","top","side","back"]
| .performanceBudget={qualityPriority:"open sloped silhouette, pale jade inclusions and readable mountain-cloud relief",targetTriangles:2200,maxTriangles:3200,maxDrawCalls:4,textureSize:512,fpsTarget:60,optimizationPolicy:"Preserve the open center, sloped lip, continuous jade maps and front relief; simplify hidden liner underside first."}
| .buildPasses|=map(.componentRefs=["root","jade-body","jade-inclusions","gold-liner","turquoise-relief","gold-ridges"])
| .risks=["Runtime transparency is avoided because dense Cocos pile lighting can make pale jade disappear.","Very weak emission only lifts dead shadows and must never make the jade look self-luminous.","Honey-russet must remain localized; a continuous dark lower band recreates the rejected result.","Single-image PBR maps are evidence only; runtime fixed-camera renders remain authoritative."]
