def recipe($a;$b;$class): {dominantAlbedo:$a,secondaryAlbedo:$b,materialClass:$class,materialClassConfidence:0.9,colorGradient:{type:"linear",stops:[{position:0,color:$a},{position:1,color:$b}]}};
def pbr($id): {usable:true,confidence:0.86,estimatedFidelity:0.86,targetThreshold:0.7,sourceImage:"design/antique-theme/yuzhuo-v2/yuzhuo-concept-sheet-v1.png",maps:{albedo:{path:("design/antique-theme/yuzhuo-v2/reference-pbr/"+$id+"/"+$id+"_albedo.png"),url:($id+"_albedo.png")},roughness:{path:("design/antique-theme/yuzhuo-v2/reference-pbr/"+$id+"/"+$id+"_roughness.png"),url:($id+"_roughness.png")},height:{path:("design/antique-theme/yuzhuo-v2/reference-pbr/"+$id+"/"+$id+"_height.png"),url:($id+"_height.png")},normal:{path:("design/antique-theme/yuzhuo-v2/reference-pbr/"+$id+"/"+$id+"_normal.png"),url:($id+"_normal.png")},ao:{path:("design/antique-theme/yuzhuo-v2/reference-pbr/"+$id+"/"+$id+"_ao.png"),url:($id+"_ao.png")}}};
def attach($parent): {parentId:$parent,parentSocket:($parent+"-surface"),localStart:[0,0,0],localEnd:[0,0,0.03],contactType:"overlap",overlap:0.02,gapTolerance:0.01,evidenceRefs:["hero","top","side"]};

. as $spec
| .preSpecAssessment.objectClass={primaryType:"white-emerald-jade-bangle",primaryDomain:"object",formLanguage:["true-round","continuous-ring","hand-polished","cloud-repaired"],structureKind:["continuous-torus","material-marbling","wrapped-collar","cloud-plaque"],motionPotential:["rigid-body","flat-spin","tumble"],materialFamilies:["creamy-jade","imperial-emerald","antique-gold"],notes:"A premium true-round jade bangle identified by a creamy-white ground, broad flowing emerald roots, soft low-contrast grain, an even circular tube section, and one restrained antique-gold four-lobed cloud repair clasp."}
| .preSpecAssessment.complexity.scores={silhouetteComplexity:2,componentCount:2,hierarchyDepth:2,repetitionDensity:2,materialLayerCount:2,localDetailDensity:3,occlusionRisk:1,actionReadinessNeed:1}
| .preSpecAssessment.complexity.estimatedCounts={macroComponents:3,mesoComponents:3,microFeatureGroups:2,materialLayers:2,repetitionSystems:2}
| .preSpecAssessment.specDepthDecision.needsRepetitionSystems=true
| .preSpecAssessment.specDepthDecision.needsMaterialLocalOverrides=true
| .preSpecAssessment.unknownsToResolveBeforeImplementation=[]
| .preSpecAssessment.detailInventory.details=[
 {id:"plump-round-section",kind:"contour",description:"Very full round-section continuous bangle",region:{x:0.03,y:0.04,width:0.63,height:0.73,units:"normalized"},scale:"macro",affects:"primary ring silhouette",mapsTo:{type:"component.localFeatures",ref:"full-round-section"},evidenceRef:"hero",confidence:0.98},
 {id:"open-center",kind:"hole",description:"Clean continuous central opening visible from all ring views",region:{x:0.17,y:0.18,width:0.4,height:0.42,units:"normalized"},scale:"macro",affects:"bangle recognition and collision",mapsTo:{type:"component.localFeatures",ref:"continuous-inner-opening"},evidenceRef:"top",confidence:0.99},
 {id:"round-proportion",kind:"contour",description:"True circular major ring with an even circular tube section",region:{x:0.02,y:0.02,width:0.66,height:0.76,units:"normalized"},scale:"meso",affects:"stable round bangle reading",mapsTo:{type:"component.localFeatures",ref:"true-round-proportion"},evidenceRef:"side",confidence:0.98},
 {id:"emerald-roots",kind:"stain",description:"Broad continuous imperial-emerald floating-color clouds",region:{x:0.03,y:0.04,width:0.63,height:0.73,units:"normalized"},scale:"meso",affects:"jade material identity",mapsTo:{type:"component.localFeatures",ref:"flowing-emerald-roots"},evidenceRef:"hero",confidence:0.97},
 {id:"soft-jade-grain",kind:"stain",description:"Soft low-contrast jade grain inside emerald regions",region:{x:0.03,y:0.04,width:0.63,height:0.73,units:"normalized"},scale:"micro",affects:"natural stone credibility without crack-like lines",mapsTo:{type:"component.localFeatures",ref:"soft-jade-grain"},evidenceRef:"hero",confidence:0.94},
 {id:"gold-cloud-clasp",kind:"fastener",description:"One wrapped antique-gold collar with four-lobed cloud plaque",region:{x:0.01,y:0.22,width:0.18,height:0.22,units:"normalized"},scale:"meso",affects:"ancient repair identity and orientation",mapsTo:{type:"component.localFeatures",ref:"four-lobed-cloud"},evidenceRef:"hero",confidence:0.97}
]
| .viewEvidence=[{id:"hero",view:"three-quarter",imageRegion:{x:0,y:0,width:0.7,height:0.8,units:"normalized"},observations:["plump round section","cream and emerald marbling","gold cloud repair"],confidence:0.98},{id:"top",view:"top",imageRegion:{x:0.62,y:0.05,width:0.38,height:0.48,units:"normalized"},observations:["continuous opening","marbling distribution","clasp position"],confidence:0.97},{id:"side",view:"side",imageRegion:{x:0.15,y:0.74,width:0.8,height:0.26,units:"normalized"},observations:["full tube thickness","stable contact","wrapped collar"],confidence:0.96},{id:"game",view:"fixed-game-camera",imageRegion:{x:0,y:0,width:1,height:1,units:"normalized"},observations:["mobile pile readability"],confidence:1.0}]
| ($spec.componentTree[0]) as $b
| .componentTree=[
 ($b|.id="root"|.name="White Emerald Jade Bangle Assembly"|.role="container"|.primitive="torus"|.topologyClass="assembled-solid"|.topologyRationale="Root groups the continuous jade ring and the compact wrapped gold repair."|.material="jade"|.materialLayers=["jade","gold"]|.localFeatures=[]|.colorMaterialRecipe=recipe("rgba(199,191,155,1)";"rgba(14,74,18,1)";"stone")|.evidenceRefs=["hero","top","side"]),
 ($b|.id="jade-ring"|.name="True-round jade bangle"|.role="body"|.level="macro"|.parent="root"|.attachment=attach("root")|.primitive="torus"|.topologyClass="continuous-sculpt"|.topologyRationale="One closed manifold torus preserves a true circular major ring, even circular tube section, and generous central opening."|.material="jade"|.materialLayers=["jade"]|.localFeatures=[{id:"full-round-section",type:"deformation",placement:"entire ring",size:0.25,orientation:"radial",geometryEffect:"even circular tube section with traditional bangle proportion",materialEffect:"broad polished highlights",confidence:0.98},{id:"continuous-inner-opening",type:"hole",placement:"ring center",size:0.68,orientation:"through",geometryEffect:"generous uninterrupted circular central void",materialEffect:"inner-rim shading",confidence:0.99},{id:"true-round-proportion",type:"contour",placement:"major and minor radii",size:1.0,orientation:"concentric",geometryEffect:"true circular outer and inner silhouettes",materialEffect:"none",confidence:0.98}]|.colorMaterialRecipe=recipe("rgba(202,195,162,1)";"rgba(75,126,53,1)";"stone")|.evidenceRefs=["hero","top","side"]),
 ($b|.id="marbling"|.name="Continuous emerald floating-color system"|.role="surface-relief"|.level="meso"|.parent="jade-ring"|.attachment=attach("jade-ring")|.primitive="torus"|.topologyClass="material-only"|.topologyRationale="A wrapped UV field carries broad cream-to-emerald color roots continuously across mesh faces without raised mosaic geometry."|.material="jade"|.materialLayers=["jade"]|.localFeatures=[{id:"flowing-emerald-roots",type:"stain",placement:"distributed around ring",size:0.62,orientation:"flowing around circumference",geometryEffect:"none",materialEffect:"broad organic emerald clouds",confidence:0.97}]|.colorMaterialRecipe=recipe("rgba(211,204,172,1)";"rgba(37,111,43,1)";"stone")|.evidenceRefs=["hero","top"]),
 ($b|.id="grain-system"|.name="Soft jade grain"|.role="surface-relief"|.level="meso"|.parent="marbling"|.attachment=attach("marbling")|.primitive="torus"|.topologyClass="material-only"|.topologyRationale="Low-contrast grain is encoded inside the same wrapped jade texture and never forms dark crack-like lines."|.material="jade"|.materialLayers=["jade"]|.localFeatures=[{id:"soft-jade-grain",type:"stain",placement:"inside emerald roots only",size:0.035,orientation:"diffuse multi-directional",geometryEffect:"none",materialEffect:"soft green grain without black lines",confidence:0.94}]|.colorMaterialRecipe=recipe("rgba(91,137,72,1)";"rgba(48,108,52,1)";"stone")|.evidenceRefs=["hero","top"]),
 ($b|.id="repair-collar"|.name="Wrapped antique-gold repair collar"|.role="connector"|.level="macro"|.parent="jade-ring"|.attachment=attach("jade-ring")|.primitive="torus"|.topologyClass="conforming-shell"|.topologyRationale="A thin closed gold collar wraps the jade tube with visible contact and no floating gap."|.material="gold"|.materialLayers=["gold"]|.localFeatures=[{id:"wrapped-gold-collar",type:"fastener",placement:"upper-left ring section",size:0.11,orientation:"around tube cross-section",geometryEffect:"thin conforming repair band",materialEffect:"dark antique gold",confidence:0.97}]|.colorMaterialRecipe=recipe("rgba(84,27,2,1)";"rgba(154,75,10,1)";"metal")|.evidenceRefs=["hero","side"]),
 ($b|.id="cloud-plaque"|.name="Four-lobed gold cloud plaque"|.role="ornament"|.level="meso"|.parent="repair-collar"|.attachment=attach("repair-collar")|.primitive="instanced-cluster"|.topologyClass="assembled-solid"|.topologyRationale="Four overlapping low solids form a compact clover-like cloud plaque with a smaller worn highlight layer."|.material="gold"|.materialLayers=["gold"]|.localFeatures=[{id:"four-lobed-cloud",type:"ridge",placement:"top of repair collar",size:0.24,orientation:"four-way",geometryEffect:"low four-lobed cloud silhouette",materialEffect:"dark base with worn gold center",confidence:0.97}]|.colorMaterialRecipe=recipe("rgba(73,21,1,1)";"rgba(167,78,8,1)";"metal")|.evidenceRefs=["hero","top"])
]
| ($spec.materials[0]) as $m
| .materials=[
 ($m|.id="jade"|.name="Creamy white jade with imperial emerald roots"|.baseColor="#C9C2A1"|.color="#C9C2A1"|.roughness.base=0.24|.metalness=0.0|.localOverrides=[{id:"emerald-roots",region:"broad flowing zones",color:"#2F7937",roughness:0.25,strength:0.72,evidenceRefs:["hero","top"]},{id:"soft-grain",region:"diffuse low-contrast variation inside green zones",color:"#4F8650",roughness:0.27,strength:0.14,evidenceRefs:["hero"]}]|.referencePbr=pbr("jade")),
 ($m|.id="gold"|.name="Antique gold repair"|.baseColor="#541B02"|.color="#541B02"|.roughness.base=0.38|.metalness=0.52|.localOverrides=[{id:"worn-cloud-center",region:"inner cloud lobes",color:"#A64D08",roughness:0.29,strength:0.38,evidenceRefs:["hero","top"]},{id:"collar-recess",region:"collar underside contact",color:"#351001",roughness:0.56,strength:0.45,evidenceRefs:["side"]}]|.referencePbr=pbr("gold"))
]
| .repetitionSystems=[{id:"continuous-marble-field",type:"linear-array",count:8,componentRef:"marbling",distribution:"overlapping low-frequency fields around wrapped UV circumference",geometry:{spacing:0.125,overlap:0.5},buildsGeometry:false,evidenceRefs:["hero","top","side"]},{id:"four-cloud-lobes",type:"radial-array",count:4,componentRef:"cloud-plaque",distribution:"four compact lobes around plaque center",geometry:{radius:0.11,overlap:0.05},buildsGeometry:true,evidenceRefs:["hero","top"]}]
| .featureReviewTargets=[{id:"jade-silhouette",name:"Plump continuous ring and open center",tier:"critical",passIds:["blockout","form-refinement"],minimumScore:0.9,mustPass:true,componentRefs:["jade-ring"],evidenceRefs:["hero","top","side"]},{id:"continuous-marbling",name:"Cream base and broad emerald roots without mosaic blocks or dark crack lines",tier:"critical",passIds:["surface-pass","material-pass"],minimumScore:0.88,mustPass:true,componentRefs:["marbling","grain-system"],evidenceRefs:["hero","top"]},{id:"cloud-repair",name:"Wrapped collar and compact four-lobed cloud plaque",tier:"critical",passIds:["structural-pass","form-refinement"],minimumScore:0.85,mustPass:true,componentRefs:["repair-collar","cloud-plaque"],evidenceRefs:["hero","side"]},{id:"game-readability",name:"Mobile fixed-camera ring, green roots and gold clasp readability",tier:"critical",passIds:["optimization-pass","lighting-pass"],minimumScore:0.84,mustPass:true,componentRefs:["root","jade-ring","cloud-plaque"],evidenceRefs:["game"]}]
| .lightingFromPhoto=["key light: broad warm upper-left light reveals the round polished jade section","fill light: soft neutral fill preserves cream ground and broad emerald roots without black lines","rim/environment: restrained studio reflection defines the continuous inner opening","contact shadow: soft coherent ground shadow confirms tube thickness and stable ring contact","exposure: 0.0; tone mapping: AgX Medium High Contrast"]
| .qualityTargets.targetFidelity=0.88
| .qualityTargets.reviewViewpoints=["fixed-game-three-quarter","top","side","back"]
| .performanceBudget={qualityPriority:"continuous jade marbling, open ring silhouette, and compact gold repair readability",targetTriangles:2800,maxTriangles:3800,maxDrawCalls:4,textureSize:512,fpsTarget:60,optimizationPolicy:"Preserve open center, full round section, wrapped jade texture, collar and cloud plaque; simplify hidden clasp undersides first."}
| .buildPasses|=map(.componentRefs=["root","jade-ring","marbling","grain-system","repair-collar","cloud-plaque"])
| .risks=["Transparent jade is intentionally avoided because dense Cocos pile lighting can make the ring disappear.","Marbling must remain continuous across mesh faces; per-face palette blocks recreate the rejected mosaic result.","The repair clasp stays compact and must not turn the bangle into a flower-shaped bracelet.","Single-image PBR maps are evidence only; runtime lighting remains the material authority."]
