def recipe($a;$b;$class): {dominantAlbedo:$a,secondaryAlbedo:$b,materialClass:$class,materialClassConfidence:0.9,colorGradient:{type:"linear",stops:[{position:0,color:$a},{position:1,color:$b}]}};
def pbr($id): {usable:true,confidence:0.86,estimatedFidelity:0.86,targetThreshold:0.7,sourceImage:"design/antique-theme/hulu-v2/hulu-concept-sheet-v2.png",maps:{albedo:{path:("design/antique-theme/hulu-v2/reference-pbr/"+$id+"/"+$id+"_albedo.png"),url:($id+"_albedo.png")},roughness:{path:("design/antique-theme/hulu-v2/reference-pbr/"+$id+"/"+$id+"_roughness.png"),url:($id+"_roughness.png")},height:{path:("design/antique-theme/hulu-v2/reference-pbr/"+$id+"/"+$id+"_height.png"),url:($id+"_height.png")},normal:{path:("design/antique-theme/hulu-v2/reference-pbr/"+$id+"/"+$id+"_normal.png"),url:($id+"_normal.png")},ao:{path:("design/antique-theme/hulu-v2/reference-pbr/"+$id+"/"+$id+"_ao.png"),url:($id+"_ao.png")}}};
def attach($parent): {parentId:$parent,parentSocket:($parent+"-surface"),localStart:[0,0,0],localEnd:[0,0,0.04],contactType:"overlap",overlap:0.025,gapTolerance:0.01,evidenceRefs:["hero","side"]};

. as $spec
| .preSpecAssessment.objectClass={primaryType:"plump-honey-amber-double-gourd",primaryDomain:"object",formLanguage:["plump","double-lobed","short-waist","ornamental"],structureKind:["continuous-lathed-body","attached-neck-rim","cord-loop","surface-relief"],motionPotential:["rigid-body","tumble"],materialFamilies:["honey-amber","antique-gold","red-cord"],notes:"A compact collectible identified by a nearly spherical lower belly, full upper belly, very short waist, thin gold neck rim, compact red loop, and broad amber cloud relief."}
| .preSpecAssessment.complexity.scores={silhouetteComplexity:2,componentCount:3,hierarchyDepth:2,repetitionDensity:2,materialLayerCount:3,localDetailDensity:2,occlusionRisk:1,actionReadinessNeed:1}
| .preSpecAssessment.complexity.estimatedCounts={macroComponents:3,mesoComponents:4,microFeatureGroups:2,materialLayers:3,repetitionSystems:2}
| .preSpecAssessment.specDepthDecision.needsRepetitionSystems=true
| .preSpecAssessment.specDepthDecision.needsMaterialLocalOverrides=true
| .preSpecAssessment.unknownsToResolveBeforeImplementation=[]
| .preSpecAssessment.detailInventory.details=[
 {id:"lower-belly",kind:"contour",description:"Huge nearly spherical lower amber belly",region:{x:0.18,y:0.38,width:0.42,height:0.52,units:"normalized"},scale:"macro",affects:"primary silhouette and fullness",mapsTo:{type:"component.localFeatures",ref:"plump-lower-belly"},evidenceRef:"hero",confidence:0.98},
 {id:"upper-belly",kind:"contour",description:"Smaller but still full upper amber belly",region:{x:0.25,y:0.16,width:0.31,height:0.34,units:"normalized"},scale:"macro",affects:"double-gourd recognition",mapsTo:{type:"component.localFeatures",ref:"round-upper-belly"},evidenceRef:"hero",confidence:0.98},
 {id:"short-waist",kind:"groove",description:"Very short pinched waist joining both lobes continuously",region:{x:0.3,y:0.38,width:0.2,height:0.12,units:"normalized"},scale:"meso",affects:"compact plump proportion",mapsTo:{type:"component.localFeatures",ref:"short-pinched-waist"},evidenceRef:"side",confidence:0.97},
 {id:"gold-neck",kind:"ridge",description:"Thin antique-gold rim around the short neck",region:{x:0.32,y:0.09,width:0.15,height:0.1,units:"normalized"},scale:"meso",affects:"material separation and top finish",mapsTo:{type:"component.localFeatures",ref:"thin-gold-neck-rim"},evidenceRef:"hero",confidence:0.96},
 {id:"red-cord",kind:"linework",description:"Compact red suspension loop and short Chinese knot",region:{x:0.33,y:0,width:0.15,height:0.19,units:"normalized"},scale:"meso",affects:"top silhouette and auspicious identity",mapsTo:{type:"component.localFeatures",ref:"compact-red-loop"},evidenceRef:"hero",confidence:0.96},
 {id:"cloud-relief",kind:"ridge",description:"Broad shallow same-material cloud scroll on the lower belly",region:{x:0.24,y:0.52,width:0.34,height:0.25,units:"normalized"},scale:"meso",affects:"ancient ornamental identity",mapsTo:{type:"component.localFeatures",ref:"broad-cloud-scroll"},evidenceRef:"hero",confidence:0.93}
]
| .viewEvidence=[{id:"hero",view:"three-quarter",imageRegion:{x:0,y:0,width:0.58,height:0.92,units:"normalized"},observations:["full double-lobed silhouette","gold neck rim","red loop","cloud relief"],confidence:0.97},{id:"side",view:"side",imageRegion:{x:0.55,y:0.05,width:0.45,height:0.9,units:"normalized"},observations:["near-spherical lower belly","short waist","stable foot"],confidence:0.95},{id:"game",view:"fixed-game-camera",imageRegion:{x:0,y:0,width:1,height:1,units:"normalized"},observations:["mobile pile readability"],confidence:1.0}]
| ($spec.componentTree[0]) as $b
| .componentTree=[
 ($b|.id="root"|.name="Honey Amber Gourd Assembly"|.role="container"|.primitive="cylinder"|.topologyClass="assembled-solid"|.topologyRationale="Root groups the continuous amber body and compact ornamental attachments."|.material="amber"|.materialLayers=["amber","gold","cord"]|.localFeatures=[]|.colorMaterialRecipe=recipe("rgba(114,32,2,1)";"rgba(239,128,11,1)";"stone")|.evidenceRefs=["hero","side"]),
 ($b|.id="amber-body"|.name="Continuous plump double-gourd body"|.role="body"|.level="macro"|.parent="root"|.attachment=attach("root")|.primitive="lathe"|.topologyClass="continuous-sculpt"|.topologyRationale="A single lathed profile forms both full lobes and the short pinched waist without sphere intersections."|.material="amber"|.materialLayers=["amber"]|.localFeatures=[{id:"plump-lower-belly",type:"deformation",placement:"lower body",size:0.92,orientation:"radial",geometryEffect:"nearly spherical dominant lower lobe",materialEffect:"deep honey edge and warm highlight",confidence:0.98},{id:"round-upper-belly",type:"deformation",placement:"upper body",size:0.72,orientation:"radial",geometryEffect:"full secondary upper lobe",materialEffect:"golden amber highlight",confidence:0.98},{id:"short-pinched-waist",type:"crease",placement:"between lobes",size:0.12,orientation:"horizontal",geometryEffect:"brief inward transition",materialEffect:"burnt amber recess",confidence:0.97}]|.colorMaterialRecipe=recipe("rgba(96,22,1,1)";"rgba(231,93,3,1)";"stone")|.evidenceRefs=["hero","side"]),
 ($b|.id="stable-foot"|.name="Low amber standing foot"|.role="support"|.level="macro"|.parent="amber-body"|.attachment=attach("amber-body")|.primitive="cylinder"|.topologyClass="assembled-solid"|.topologyRationale="A shallow hidden foot gives reliable pile contact while preserving the spherical belly."|.material="amber"|.materialLayers=["amber"]|.localFeatures=[]|.colorMaterialRecipe=recipe("rgba(75,14,1,1)";"rgba(153,43,2,1)";"stone")|.evidenceRefs=["side","game"]),
 ($b|.id="gold-neck-rim"|.name="Thin antique-gold neck rim"|.role="rim"|.level="macro"|.parent="amber-body"|.attachment=attach("amber-body")|.primitive="torus"|.topologyClass="assembled-solid"|.topologyRationale="A thin closed gold rim finishes the short neck and visibly overlaps the amber body."|.material="gold"|.materialLayers=["gold"]|.localFeatures=[{id:"thin-gold-neck-rim",type:"ridge",placement:"neck top",size:0.14,orientation:"horizontal ring",geometryEffect:"thin raised circular rim",materialEffect:"warm metallic edge",confidence:0.96}]|.colorMaterialRecipe=recipe("rgba(96,37,2,1)";"rgba(194,106,13,1)";"metal")|.evidenceRefs=["hero","side"]),
 ($b|.id="red-loop"|.name="Compact red suspension loop"|.role="connector"|.level="meso"|.parent="gold-neck-rim"|.attachment=attach("gold-neck-rim")|.primitive="curve-sweep"|.topologyClass="fiber-strand"|.topologyRationale="A swept cord curve creates a compact closed hanging loop above the neck."|.material="cord"|.materialLayers=["cord"]|.localFeatures=[{id:"compact-red-loop",type:"deformation",placement:"above neck",size:0.3,orientation:"vertical",geometryEffect:"short rounded cord loop",materialEffect:"saturated red fabric",confidence:0.96}]|.colorMaterialRecipe=recipe("rgba(91,3,2,1)";"rgba(192,22,8,1)";"fabric")|.evidenceRefs=["hero"]),
 ($b|.id="red-knot"|.name="Short Chinese cord knot"|.role="ornament"|.level="meso"|.parent="red-loop"|.attachment=attach("red-loop")|.primitive="instanced-cluster"|.topologyClass="fiber-strand"|.topologyRationale="Short overlapping cord segments form a compact knot without an oversized tassel."|.material="cord"|.materialLayers=["cord"]|.localFeatures=[{id:"short-knot",type:"ridge",placement:"loop base",size:0.13,orientation:"crossed",geometryEffect:"compact crossed knot",materialEffect:"dark red contact shadow",confidence:0.93}]|.colorMaterialRecipe=recipe("rgba(76,2,1,1)";"rgba(170,16,5,1)";"fabric")|.evidenceRefs=["hero"]),
 ($b|.id="cloud-relief"|.name="Broad amber cloud-scroll relief"|.role="surface-relief"|.level="meso"|.parent="amber-body"|.attachment=attach("amber-body")|.primitive="curve-sweep"|.topologyClass="surface-relief"|.topologyRationale="A shallow swept scroll follows the lower-belly surface and remains the same amber material family."|.material="amber"|.materialLayers=["amber"]|.localFeatures=[{id:"broad-cloud-scroll",type:"ridge",placement:"front lower belly",size:0.48,orientation:"horizontal scroll",geometryEffect:"low broad cloud curl",materialEffect:"slightly darker honey amber",confidence:0.93}]|.colorMaterialRecipe=recipe("rgba(102,25,1,1)";"rgba(184,59,2,1)";"stone")|.evidenceRefs=["hero","game"])
]
| ($spec.materials[0]) as $m
| .materials=[
 ($m|.id="amber"|.name="Saturated honey amber"|.baseColor="#B54109"|.color="#B54109"|.roughness.base=0.3|.metalness=0.01|.localOverrides=[{id:"belly-highlight",region:"upper-left lobe planes",color:"#F19311",roughness:0.22,strength:0.42,evidenceRefs:["hero"]},{id:"waist-recess",region:"short waist and relief roots",color:"#84220A",roughness:0.4,strength:0.5,evidenceRefs:["hero","side"]}]|.referencePbr=pbr("amber")),
 ($m|.id="gold"|.name="Antique gold neck rim"|.baseColor="#A8660C"|.color="#A8660C"|.roughness.base=0.4|.metalness=0.55|.localOverrides=[{id:"worn-edge",region:"neck rim upper edge",color:"#D59B2B",roughness:0.28,strength:0.35,evidenceRefs:["hero"]},{id:"rim-recess",region:"underside contact",color:"#5C2602",roughness:0.58,strength:0.45,evidenceRefs:["side"]}]|.referencePbr=pbr("gold")),
 ($m|.id="cord"|.name="Saturated red woven cord"|.baseColor="#A51108"|.color="#A51108"|.roughness.base=0.72|.metalness=0.0|.localOverrides=[{id:"cord-highlight",region:"outer loop",color:"#D42A13",roughness:0.58,strength:0.3,evidenceRefs:["hero"]},{id:"knot-shadow",region:"crossed knot contacts",color:"#570201",roughness:0.82,strength:0.48,evidenceRefs:["hero"]}]|.referencePbr=pbr("cord"))
]
| .repetitionSystems=[{id:"body-rib-sectors",type:"radial-array",count:8,componentRef:"amber-body",distribution:"subtle vertical honey-amber planes around both lobes",geometry:{radius:0.9,overlap:0.0},buildsGeometry:true,evidenceRefs:["hero","side"]},{id:"knot-crossings",type:"linear-array",count:4,componentRef:"red-knot",distribution:"compact crossed cord pieces at loop base",geometry:{spacing:0.035,overlap:0.02},buildsGeometry:true,evidenceRefs:["hero"]}]
| .featureReviewTargets=[{id:"plump-silhouette",name:"Full lower and upper lobes with very short waist",tier:"critical",passIds:["blockout","form-refinement"],minimumScore:0.9,mustPass:true,componentRefs:["amber-body"],evidenceRefs:["hero","side"]},{id:"neck-and-loop",name:"Thin gold rim and compact red loop",tier:"critical",passIds:["structural-pass","material-pass"],minimumScore:0.85,mustPass:true,componentRefs:["gold-neck-rim","red-loop","red-knot"],evidenceRefs:["hero"]},{id:"cloud-relief",name:"Broad shallow same-material cloud scroll",tier:"critical",passIds:["surface-pass"],minimumScore:0.84,mustPass:true,componentRefs:["cloud-relief"],evidenceRefs:["hero","game"]},{id:"amber-color",name:"Saturated honey-orange amber with burnt recesses",tier:"critical",passIds:["material-pass","lighting-pass"],minimumScore:0.86,mustPass:true,componentRefs:["amber-body","cloud-relief"],evidenceRefs:["hero","game"]},{id:"game-readability",name:"Mobile fixed-camera gourd readability",tier:"critical",passIds:["optimization-pass"],minimumScore:0.84,mustPass:true,componentRefs:["root","amber-body","red-loop"],evidenceRefs:["game"]}]
| .lightingFromPhoto=["key light: broad warm upper-left light reveals the full double-lobed silhouette","fill light: restrained cool frontal fill keeps the burnt amber waist readable","rim/environment: neutral studio reflection separates honey amber from the background","contact shadow: soft coherent shadow under the low foot proves stable ground contact","exposure: 0.0; tone mapping: AgX Medium High Contrast"]
| .qualityTargets.targetFidelity=0.86
| .qualityTargets.reviewViewpoints=["fixed-game-three-quarter","front","side","back"]
| .performanceBudget={qualityPriority:"mobile silhouette, saturated amber separation, and compact ornament readability",targetTriangles:2300,maxTriangles:3500,maxDrawCalls:8,textureSize:512,fpsTarget:60,optimizationPolicy:"Preserve both lobe profiles, short waist, neck rim, cord loop, and cloud scroll; simplify hidden foot and knot segments first."}
| .buildPasses|=map(.componentRefs=["root","amber-body","stable-foot","gold-neck-rim","red-loop","red-knot","cloud-relief"])
| .risks=["Amber remains opaque in runtime because transparent shading can disappear in the dense Cocos pile.","The upper lobe must stay full; shrinking it would recreate the rejected bottle silhouette.","Single-image PBR maps are evidence only; runtime lighting remains the material authority."]
