def recipe($a;$b;$class): {dominantAlbedo:$a,secondaryAlbedo:$b,materialClass:$class,materialClassConfidence:0.9,colorGradient:{type:"radial",stops:[{position:0,color:$a},{position:1,color:$b}]}};
def pbr($id): {usable:true,confidence:0.86,estimatedFidelity:0.86,targetThreshold:0.7,sourceImage:"design/antique-theme/bracelet-v2/bracelet-concept-sheet-v1.png",maps:{albedo:{path:("design/antique-theme/bracelet-v2/reference-pbr/"+$id+"/"+$id+"_albedo.png"),url:($id+"_albedo.png")},roughness:{path:("design/antique-theme/bracelet-v2/reference-pbr/"+$id+"/"+$id+"_roughness.png"),url:($id+"_roughness.png")},height:{path:("design/antique-theme/bracelet-v2/reference-pbr/"+$id+"/"+$id+"_height.png"),url:($id+"_height.png")},normal:{path:("design/antique-theme/bracelet-v2/reference-pbr/"+$id+"/"+$id+"_normal.png"),url:($id+"_normal.png")},ao:{path:("design/antique-theme/bracelet-v2/reference-pbr/"+$id+"/"+$id+"_ao.png"),url:($id+"_ao.png")}}};
def attach($parent): {parentId:$parent,parentSocket:($parent+"-surface"),localStart:[0,0,0],localEnd:[0,0,0.04],contactType:"overlap",overlap:0.025,gapTolerance:0.01,evidenceRefs:["hero","top","side"]};

. as $spec
| .preSpecAssessment.objectClass={primaryType:"amethyst-bead-bracelet",primaryDomain:"object",formLanguage:["radial","faceted","beaded","pendant-oriented"],structureKind:["elastic-ring","radial-array","linked-charm"],motionPotential:["rigid-body","flat-spin"],materialFamilies:["amethyst","antique-gold","pale-jade","woven-cord"],notes:"A compact jewelry collectible identified by discrete faceted beads, gold rhythm points, one focal bead, and a pale jade pendant."}
| .preSpecAssessment.complexity.scores={silhouetteComplexity:2,componentCount:3,hierarchyDepth:2,repetitionDensity:3,materialLayerCount:3,localDetailDensity:2,occlusionRisk:2,actionReadinessNeed:1}
| .preSpecAssessment.complexity.estimatedCounts={macroComponents:4,mesoComponents:3,microFeatureGroups:2,materialLayers:4,repetitionSystems:2}
| .preSpecAssessment.specDepthDecision.needsRepetitionSystems=true
| .preSpecAssessment.specDepthDecision.needsMaterialLocalOverrides=true
| .preSpecAssessment.unknownsToResolveBeforeImplementation=[]
| .preSpecAssessment.detailInventory.details=[
 {id:"faceted-beads",kind:"ridge",description:"Twelve individually readable low-poly amethyst beads",region:{x:0.02,y:0.05,width:0.72,height:0.58,units:"normalized"},scale:"meso",affects:"silhouette and gemstone highlight",mapsTo:{type:"component.localFeatures",ref:"faceted-cuts"},evidenceRef:"hero",confidence:0.97},
 {id:"gold-spacers",kind:"ridge",description:"Three compact antique-gold rhythm points",region:{x:0.05,y:0.08,width:0.68,height:0.52,units:"normalized"},scale:"meso",affects:"material separation",mapsTo:{type:"component.localFeatures",ref:"radial-spacers"},evidenceRef:"top",confidence:0.95},
 {id:"visible-cord",kind:"groove",description:"Wine-red elastic visible in bead gaps",region:{x:0.12,y:0.12,width:0.56,height:0.45,units:"normalized"},scale:"micro",affects:"construction credibility",mapsTo:{type:"component.localFeatures",ref:"gap-cord"},evidenceRef:"hero",confidence:0.86},
 {id:"focal-cloud",kind:"ridge",description:"Broad original cloud-scroll relief on enlarged front bead",region:{x:0.24,y:0.29,width:0.22,height:0.24,units:"normalized"},scale:"meso",affects:"orientation and identity",mapsTo:{type:"component.localFeatures",ref:"cloud-relief"},evidenceRef:"hero",confidence:0.93},
 {id:"gold-loop",kind:"ridge",description:"True open loop between focal bead and pendant",region:{x:0.28,y:0.48,width:0.12,height:0.12,units:"normalized"},scale:"micro",affects:"attachment readability",mapsTo:{type:"component.localFeatures",ref:"open-loop"},evidenceRef:"side",confidence:0.92},
 {id:"jade-drop",kind:"ridge",description:"Pale jade teardrop that breaks the circular silhouette",region:{x:0.27,y:0.54,width:0.16,height:0.25,units:"normalized"},scale:"macro",affects:"silhouette and category",mapsTo:{type:"component.localFeatures",ref:"teardrop-form"},evidenceRef:"hero",confidence:0.97}
]
| .viewEvidence=[{id:"hero",view:"three-quarter",imageRegion:{x:0,y:0,width:0.75,height:0.62,units:"normalized"},observations:["faceted purple beads","gold spacers","focal bead","jade pendant"],confidence:0.97},{id:"top",view:"top",imageRegion:{x:0.12,y:0.52,width:0.48,height:0.46,units:"normalized"},observations:["radial spacing","open center","pendant orientation"],confidence:0.96},{id:"side",view:"side",imageRegion:{x:0.73,y:0.1,width:0.27,height:0.82,units:"normalized"},observations:["bead thickness","loop attachment","pendant depth"],confidence:0.94},{id:"game",view:"fixed-game-camera",imageRegion:{x:0,y:0,width:1,height:1,units:"normalized"},observations:["thumbnail readability"],confidence:1.0}]
| ($spec.componentTree[0]) as $b
| .componentTree=[
 ($b|.id="root"|.name="Bracelet Assembly"|.role="container"|.primitive="torus"|.topologyClass="assembled-solid"|.topologyRationale="Root groups a repeated bead ring and linked pendant."|.material="amethyst"|.materialLayers=["amethyst","gold","jade","cord"]|.localFeatures=[]|.colorMaterialRecipe=recipe("rgba(78,18,128,1)";"rgba(202,111,32,1)";"stone")|.evidenceRefs=["hero","top"]),
 ($b|.id="cord"|.name="Elastic cord ring"|.role="connector"|.level="macro"|.parent="root"|.attachment=attach("root")|.primitive="torus"|.topologyClass="continuous-sculpt"|.topologyRationale="A continuous torus passes behind all bead gaps."|.material="cord"|.materialLayers=["cord"]|.localFeatures=[{id:"gap-cord",type:"connector",placement:"between radial beads",size:0.045,orientation:"radial",geometryEffect:"visible continuous elastic ring",materialEffect:"matte wine-red",confidence:0.9}]|.colorMaterialRecipe=recipe("rgba(46,3,10,1)";"rgba(93,10,23,1)";"fabric")|.evidenceRefs=["hero","top"]),
 ($b|.id="bead-system"|.name="Faceted amethyst bead system"|.role="body"|.level="macro"|.parent="root"|.attachment=attach("root")|.primitive="sphere"|.topologyClass="assembled-solid"|.topologyRationale="Separate faceted icospheres preserve bead gaps and radial repetition."|.material="amethyst"|.materialLayers=["amethyst"]|.localFeatures=[{id:"faceted-cuts",type:"ridge",placement:"all bead surfaces",size:0.08,orientation:"multi-plane",geometryEffect:"low-poly gemstone facets",materialEffect:"alternating violet highlights",confidence:0.96}]|.colorMaterialRecipe=recipe("rgba(76,18,128,1)";"rgba(145,48,190,1)";"stone")|.evidenceRefs=["hero","top","side"]),
 ($b|.id="spacer-system"|.name="Antique-gold spacer system"|.role="ornament"|.level="macro"|.parent="root"|.attachment=attach("root")|.primitive="sphere"|.topologyClass="assembled-solid"|.topologyRationale="Three compact gold solids interrupt the purple bead rhythm."|.material="gold"|.materialLayers=["gold"]|.localFeatures=[{id:"radial-spacers",type:"ridge",placement:"three ring quadrants",size:0.15,orientation:"radial",geometryEffect:"compressed gold spacer beads",materialEffect:"warm satin metal",confidence:0.95}]|.colorMaterialRecipe=recipe("rgba(205,107,18,1)";"rgba(246,176,57,1)";"metal")|.evidenceRefs=["hero","top"]),
 ($b|.id="focal-bead"|.name="Engraved focal gold bead"|.role="ornament"|.level="meso"|.parent="root"|.attachment=attach("root")|.primitive="sphere"|.topologyClass="surface-relief"|.topologyRationale="An enlarged faceted solid carries broad raised cloud strokes."|.material="gold"|.materialLayers=["gold"]|.localFeatures=[{id:"cloud-relief",type:"ridge",placement:"top face",size:0.22,orientation:"bilateral",geometryEffect:"three broad raised original strokes",materialEffect:"dark recessed contrast",confidence:0.94}]|.colorMaterialRecipe=recipe("rgba(205,107,18,1)";"rgba(83,27,5,1)";"metal")|.evidenceRefs=["hero","side"]),
 ($b|.id="charm-loop"|.name="Open gold charm loop"|.role="connector"|.level="meso"|.parent="focal-bead"|.attachment=attach("focal-bead")|.primitive="torus"|.topologyClass="continuous-sculpt"|.topologyRationale="A true open torus visually connects the focal bead and pendant."|.material="gold"|.materialLayers=["gold"]|.localFeatures=[{id:"open-loop",type:"negative-space",placement:"below focal bead",size:0.11,orientation:"bracelet plane",geometryEffect:"visible open connector",materialEffect:"gold rim highlight",confidence:0.93}]|.colorMaterialRecipe=recipe("rgba(214,125,24,1)";"rgba(246,180,60,1)";"metal")|.evidenceRefs=["hero","side"]),
 ($b|.id="jade-charm"|.name="Pale jade drop charm"|.role="ornament"|.level="meso"|.parent="charm-loop"|.attachment=attach("charm-loop")|.primitive="sphere"|.topologyClass="continuous-sculpt"|.topologyRationale="A compressed teardrop solid breaks the circular silhouette."|.material="jade"|.materialLayers=["jade"]|.localFeatures=[{id:"teardrop-form",type:"deformation",placement:"pendant",size:0.25,orientation:"away from ring",geometryEffect:"elongated pale drop",materialEffect:"soft jade highlight",confidence:0.96}]|.colorMaterialRecipe=recipe("rgba(127,201,155,1)";"rgba(216,235,210,1)";"stone")|.evidenceRefs=["hero","side"])
]
| ($spec.materials[0]) as $m
| .materials=[
 ($m|.id="amethyst"|.name="Faceted amethyst"|.baseColor="#5B168E"|.color="#5B168E"|.roughness.base=0.3|.metalness=0.03|.localOverrides=[{id:"facet-highlights",region:"selected upward facets",color:"#A84ED2",roughness:0.24,strength:0.35,evidenceRefs:["hero","top"]}]|.referencePbr=pbr("amethyst")),
 ($m|.id="gold"|.name="Antique gold"|.baseColor="#CD711A"|.color="#CD711A"|.roughness.base=0.36|.metalness=0.52|.localOverrides=[{id:"relief-shadow",region:"cloud motif roots",color:"#5A1F08",roughness:0.58,strength:0.4,evidenceRefs:["hero"]}]|.referencePbr=pbr("gold")),
 ($m|.id="jade"|.name="Pale jade"|.baseColor="#83C99B"|.color="#83C99B"|.roughness.base=0.4|.metalness=0.0|.localOverrides=[{id:"drop-edge",region:"pendant edge",color:"#D8EBD2",roughness:0.3,strength:0.3,evidenceRefs:["hero","side"]}]|.referencePbr=pbr("jade")),
 ($m|.id="cord"|.name="Wine-red elastic"|.baseColor="#30050C"|.color="#30050C"|.roughness.base=0.8|.metalness=0.0|.localOverrides=[{id:"gap-shadow",region:"bead contacts",color:"#190207",roughness:0.88,strength:0.5,evidenceRefs:["hero"]}]|.referencePbr=pbr("amethyst"))
]
| .repetitionSystems=[{id:"radial-beads",type:"radial-array",count:12,componentRef:"bead-system",distribution:"sixteen-slot ring excluding focal and spacer slots",geometry:{radius:1.23,beadRadius:0.285},buildsGeometry:true,evidenceRefs:["hero","top"]},{id:"gold-spacers",type:"radial-array",count:3,componentRef:"spacer-system",distribution:"cardinal rhythm slots",geometry:{radius:1.23,spacerRadius:0.15},buildsGeometry:true,evidenceRefs:["hero","top"]}]
| .featureReviewTargets=[{id:"bead-ring",name:"Discrete faceted bead ring and open center",tier:"critical",passIds:["blockout","form-refinement"],minimumScore:0.86,mustPass:true,componentRefs:["cord","bead-system"],evidenceRefs:["hero","top"]},{id:"gold-rhythm",name:"Gold spacers and focal cloud bead",tier:"critical",passIds:["structural-pass","surface-pass"],minimumScore:0.84,mustPass:true,componentRefs:["spacer-system","focal-bead"],evidenceRefs:["hero","top"]},{id:"pendant-orientation",name:"Linked pale jade pendant silhouette",tier:"critical",passIds:["structural-pass","form-refinement"],minimumScore:0.86,mustPass:true,componentRefs:["charm-loop","jade-charm"],evidenceRefs:["hero","side"]},{id:"material-separation",name:"Amethyst, gold, jade and cord separation",tier:"critical",passIds:["material-pass","lighting-pass"],minimumScore:0.84,mustPass:true,componentRefs:["bead-system","spacer-system","jade-charm","cord"],evidenceRefs:["hero","game"]},{id:"game-readability",name:"Mobile fixed-camera bracelet readability",tier:"critical",passIds:["optimization-pass"],minimumScore:0.84,mustPass:true,componentRefs:["root","focal-bead","jade-charm"],evidenceRefs:["game"]}]
| .lightingFromPhoto=["key light: broad warm area light from camera upper-left with soft contact shadow","fill light: cool low-intensity camera-right fill preserves purple facets and cord gaps","rim/environment: restrained neutral environment reflection keeps gold orange rather than black","exposure: 0.0; tone mapping: AgX Medium High Contrast"]
| .qualityTargets.targetFidelity=0.86
| .qualityTargets.reviewViewpoints=["fixed-game-three-quarter","top","side","back"]
| .performanceBudget={qualityPriority:"mobile silhouette and material separation",targetTriangles:3000,maxTriangles:4000,maxDrawCalls:7,textureSize:512,fpsTarget:60,optimizationPolicy:"Preserve discrete bead gaps, focal relief and pendant silhouette; simplify hidden underside facets first."}
| .buildPasses|=map(.componentRefs=["root","cord","bead-system","spacer-system","focal-bead","charm-loop","jade-charm"])
| .risks=["The runtime uses a round-item collider proxy, so the pendant must remain compact and cannot extend far beyond the ring.","Cocos antique lighting can turn high-metalness gold dark; the exported gold relies on warm albedo with moderate metalness.","Single-image PBR maps are evidence only; game runtime screenshots remain the material authority."]
